### ISSUE TITLE
Results for DeblurNeRF's real motion blur dataset

### ISSUE THREAD

**Issue by dongwoohhh** [WU-CVGL/BAD-NeRF#7]
I'm trying to produce results for DeblurNeRF's  real motion blur dataset.

Both option for linear and cubic produce novel view render like below.

Do you recommend specific configuration for training to produce better results?

![rgb_000](https://github.com/WU-CVGL/BAD-NeRF/assets/8788980/91d6ed5c-41d6-40ac-8e3f-6e754a08a583)

**Comment by wangpeng000** [comment]
Hi Dongwoo,

I used the **linear** and only changed the **spline num** to 5 and no other specific parameters are changed in the configuration.

Unfortunately, I didn't render novel view images for real scenes but these are some rendered videos (many novel view images) that look well . So I think there may be some mistakes in your training setting? Besides, the real data results are not so perfect because the motion blur data of Deblur-NeRF are captured by manually shaking the camera, resulting in the discontinuous blur images which violates our continuous motion assumption. 


https://github.com/WU-CVGL/BAD-NeRF/assets/65640219/d5fda0cf-477b-4d6e-b5dc-e3a7ff20c69e


https://github.com/WU-CVGL/BAD-NeRF/assets/65640219/423cacf4-bb99-4951-b801-06e615866a82


https://github.com/WU-CVGL/BAD-NeRF/assets/65640219/64549ccd-0cba-408c-97f2-c2b67c51a456

**Comment by dongwoohhh** [comment]
Thanks for reply.

I think I made some mistakes, when running the code. 

Do you mean the setting you used are
- linear = True
- deblur_images = 5 ?

**Comment by wangpeng000** [comment]
Yes, you're right.

**Comment by 97littleleaf11** [comment]
@wangpeng000 could you please share your full args list on real scene? Results are still voxel-like when setting deblur_images = 5 and linear = True. I guess I missed some key settings, such as factor_pose_novel
